markdown: kramdown
url: ''
baseurl: null
title: Are the Oscars Still So White?
description: A website for researching the racial and cultural diversity of Oscar winners
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Oscars, Racial, Diversity'
favicon-url: null
heroimage: '/assert/yzq winner-image.jpeg'
email: ygaocf@connect.ust.hk
facebook_username: Yue Luna
instagram_username: patronus0420
linkedin_username: Gao Yue
github_username: gy5630
youtube_channel_id: UCdyhDK-L2K2Zl672EFtz_bw
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
author-name: HUMA5630G7
author-image: '/Users/gy/HUMA5630.github.io/yzq\ winner-image.jpeg'
author-about: >-
  We are the seventh group in the HUMA 5630 programme at the Hong Kong University of Science and Technology and we are dedicated to the study of the racial and cultural diversity of Oscar winners.
author-url: 'https://github.com/KevinAllegretti'
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
